name: Generate top dependents report
on:
  schedule:
    - cron: '0 14 * * 1'
  workflow_dispatch:
jobs:
  create-dependents-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'dependents-report/requirements.txt'
      - name: Fetch requirements
        run: python -m pip install -r dependents-report/requirements.txt
      - name: Run script
        run: python dependents-report/get-dependents.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Regenerate dependents report
          title: Regenerate dependents report
          body: This PR updates the dependents report.
          base: main
          branch: actions-regenerate-dependents-report
          delete-branch: true
          signoff: true
          author: GitHub <noreply@github.com>
          committer: GitHub <noreply@github.com>
